/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window8 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window9 (void);
GtkWidget* create_window10 (void);
GtkWidget* create_window11 (void);
GtkWidget* create_window1y (void);
GtkWidget* create_window2y (void);
GtkWidget* create_window3y (void);
GtkWidget* create_window4y (void);
GtkWidget* create_window5y (void);
GtkWidget* create_window8y (void);
GtkWidget* create_window7y (void);
GtkWidget* create_window6y (void);
GtkWidget* create_window9y (void);
GtkWidget* create_window10y (void);
GtkWidget* create_window11y (void);
